(in-package :ccl)

(defun init-action-name-mapper ()
  (let ((action-name-mapper (make-instance 'ccl::cram-2-knowrob-mapper))
    (definition
     '(("reaching" "Reaching")
       ("retracting" "Retracting")
       ("lifting" "Lifting")
       ("putting" "Lowering")
       ("setting-gripper" "SettingGripper")
       ("positioning-arm" "PositioningArm")
       ("opening" "Opening")
       ("opening-gripper" "Opening")
       ("closing" "Closing")
       ("detecting" "Detecting")
       ("placing" "Placing")
       ("picking-up" "PickingUp")
       ("releasing" "Releasing")
       ("grasping" "Grasping")
       ("gripping" "Gripping")
       ("looking" "LookingAt")
       ("going" "MovingTo")
       ("navigating" "Navigating")
       ("searching" "LookingFor")
       ("fetching" "Fetching")
       ("delivering" "Delivering")
       ("transporting" "Transporting")
       ("turning-towards" "LookingFor")
       ("sealing" "Sealing")
       ("pushing" "Pushing")
       ("pulling" "Pulling")
       ("perceiving" "Perceiving")
       ("accessing" "Accessing"))))
    (ccl::add-definition-to-mapper definition action-name-mapper)
    action-name-mapper))

(defparameter *action-name-mapper* (init-action-name-mapper))

(defun get-knowrob-action-name-uri (cram-action-name designator)
  (concatenate 'string "'http://www.ease-crc.org/ont/SOMA.owl#" (get-knowrob-action-name cram-action-name designator) "'"))

(defun get-knowrob-action-name (cram-action-name designator)
  (let* ((lower-cram-action-name (string-downcase cram-action-name))
         (knowrob-action-name (get-definition-from-mapper lower-cram-action-name *action-name-mapper*)))
    (when (not knowrob-action-name) (setf knowrob-action-name "PhysicalTask"))
    knowrob-action-name))
