version: 2
jobs:
  build:
    docker:
      - image: debian:stable

    working_directory: /src/cl-png

    steps:
      - run: apt-get update -y && apt-get install -y sbcl wget gcc libpng-dev git ssh

      - checkout

      - run: wget https://beta.quicklisp.org/quicklisp.lisp

      - run: sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval '(ql:quickload "cffi")' --quit

      - run: ln -s /src/cl-png /root/quicklisp/local-projects/png

      - run: sbcl --disable-debugger --load /root/quicklisp/setup.lisp --eval '(ql:quickload "png")' --eval "(asdf:oos 'asdf:load-op '#:png-test)" --eval "(lisp-unit:run-all-tests :png-test)" --quit

      - run: sbcl --disable-debugger --load /root/quicklisp/setup.lisp --eval '(ql:quickload "png")' --eval "(asdf:oos 'asdf:load-op '#:image-test)" --eval "(lisp-unit:run-all-tests :image-test)" --quit

      - run: sbcl --disable-debugger --load /root/quicklisp/setup.lisp --eval '(ql:quickload "png")' --eval "(asdf:oos 'asdf:load-op '#:bmp-test)" --eval "(lisp-unit:run-all-tests :bmp-test)" --quit

      - run: sbcl --disable-debugger --load /root/quicklisp/setup.lisp --eval '(ql:quickload "png")' --eval "(asdf:oos 'asdf:load-op '#:ops-test)" --eval "(lisp-unit:run-all-tests :ops-test)" --quit
