(in-package :ccl)

(defun get-knowrob-action-name-uri (cram-action-name designator)
  (concatenate 'string "'http://www.ease-crc.org/ont/EASE-ACT.owl#" (get-knowrob-action-name cram-action-name designator) "'"))

(defun get-knowrob-action-name (cram-action-name designator)
  (let ((knowrob-action-name nil))
    (cond ((string-equal cram-action-name "reaching")
           (setf knowrob-action-name "Reaching"))
          ((string-equal cram-action-name "retracting")
           (setf knowrob-action-name "Retracting"))
          ((string-equal cram-action-name "lifting")
           (setf knowrob-action-name "Lifting"))
          ((string-equal cram-action-name "putting")
           (setf knowrob-action-name "Lowering"))
          ((string-equal cram-action-name "setting-gripper")
           (setf knowrob-action-name "Positioning"))
          ((string-equal cram-action-name "POSITIONING-ARM")
           (setf knowrob-action-name "Positioning"))
          ((string-equal cram-action-name "opening")
           (setf knowrob-action-name "Opening"))
          ((string-equal cram-action-name "OPENING-GRIPPER")
           (setf knowrob-action-name "Opening"))
          ((string-equal cram-action-name "closing")
           (setf knowrob-action-name "Closing"))
          ((string-equal cram-action-name "detecting")
           (setf knowrob-action-name "Detecting"))
          ((string-equal cram-action-name "placing")
           (setf knowrob-action-name "Placing"))
          ((string-equal cram-action-name "picking-up")
           (setf knowrob-action-name "PickingUp"))
          ((string-equal cram-action-name "releasing")
           (setf knowrob-action-name "Releasing"))
          ((string-equal cram-action-name "Grasping")
           (setf knowrob-action-name "Grasping"))
          ((string-equal cram-action-name "gripping")
           (setf knowrob-action-name "Grasping"))
          ((string-equal cram-action-name "looking")
           (setf knowrob-action-name "LookingAt"))
          ((string-equal cram-action-name "going")
           (setf knowrob-action-name "MovingTo"))
          ((string-equal cram-action-name "navigating")
           (setf knowrob-action-name "Navigating"))
          ((string-equal cram-action-name "searching")
           (setf knowrob-action-name "LookingFor"))
          ((string-equal cram-action-name "fetching")
           (setf knowrob-action-name "PickingUp"))
          ((string-equal cram-action-name "delivering")
           (setf knowrob-action-name "PuttingDown"))
          ((string-equal cram-action-name "Transporting")
           (setf knowrob-action-name "Transporting"))
          ((string-equal cram-action-name "Turning-Towards")
           (setf knowrob-action-name "LookingFor"))
          ((string-equal cram-action-name "SEALING")
           (setf knowrob-action-name "Sealing"))
          ((string-equal cram-action-name "PUSHING")
           (setf knowrob-action-name "Pushing"))
          ((string-equal cram-action-name "PULLING")
           (setf knowrob-action-name "Pulling"))
          ((string-equal cram-action-name "ACCESSING")
           (setf knowrob-action-name "Accessing")))
    ;;(when (not knowrob-action-name) (progn (print cram-action-name) (break)))
    knowrob-action-name))
